### ISSUE TITLE
What is the   channelID: "DEFAULTCHANNELID" # Discord channel id which is integrated with the Minecraft channel

### ISSUE THREAD

**Issue by jackhistoria** [MineDisco/Minecraft-Discord-Bot-Bukkit#1]
Where do i find this id? The invite url doesn't work on my papermc server.
What ID is that and where do I find it? I would love to use your plugin and looking forward to it.

[12:22:03 ERROR]: [MineDisco] Logging to the Discord was not successful. Please check, is the token valid.

**Comment by Oodi** [comment]
You need first create Discord bot [http://discordapp.com/developers/applications/me](http://discordapp.com/developers/applications/me) and invite it to your server and then copy bots token to the config.yml. You can create bot by following guide [https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/](https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/) from step 1 to 4.
